"""update.

Revision ID: 0fcd5fced747
Revises: 
Create Date: 2021-04-04 23:23:08.317976

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fcd5fced747'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file_metas',
    sa.Column('location', sa.String(length=120), nullable=True),
    sa.Column('file_name', sa.String(length=40), nullable=True),
    sa.Column('file_md5', sa.String(length=40), nullable=False),
    sa.Column('file_size', sa.String(length=120), nullable=True),
    sa.Column('file_upload_at', sa.DateTime(), nullable=True),
    sa.Column('file_update_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('file_md5'),
    sa.UniqueConstraint('file_md5')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('user_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('User', sa.String(length=64), nullable=True),
    sa.Column('FileMeta', sa.String(length=40), nullable=True),
    sa.Column('file_upload_at', sa.DateTime(), nullable=True),
    sa.Column('file_size', sa.String(length=120), nullable=True),
    sa.Column('file_name', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['FileMeta'], ['file_metas.file_md5'], ),
    sa.ForeignKeyConstraint(['User'], ['users.username'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_files_FileMeta'), 'user_files', ['FileMeta'], unique=False)
    op.create_index(op.f('ix_user_files_User'), 'user_files', ['User'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_files_User'), table_name='user_files')
    op.drop_index(op.f('ix_user_files_FileMeta'), table_name='user_files')
    op.drop_table('user_files')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('file_metas')
    # ### end Alembic commands ###
