"""update.

Revision ID: 20cff6300965
Revises: 8d9923191ddd
Create Date: 2021-04-05 14:38:03.786880

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20cff6300965'
down_revision = '8d9923191ddd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_files_file_md5', table_name='user_files')
    op.drop_index('ix_user_files_username', table_name='user_files')
    op.create_foreign_key(None, 'user_files', 'users', ['username'], ['username'])
    op.create_foreign_key(None, 'user_files', 'file_metas', ['file_md5'], ['file_md5'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_files', type_='foreignkey')
    op.drop_constraint(None, 'user_files', type_='foreignkey')
    op.create_index('ix_user_files_username', 'user_files', ['username'], unique=True)
    op.create_index('ix_user_files_file_md5', 'user_files', ['file_md5'], unique=True)
    # ### end Alembic commands ###
