"""initial migration.

Revision ID: ca5f71bc110e
Revises: 
Create Date: 2021-03-25 23:00:02.294938

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca5f71bc110e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file_meta',
    sa.Column('location', sa.String(length=120), nullable=True),
    sa.Column('file_name', sa.String(length=40), nullable=True),
    sa.Column('file_md5', sa.String(length=40), nullable=False),
    sa.Column('file_size', sa.String(length=120), nullable=True),
    sa.Column('file_upload_at', sa.DateTime(), nullable=True),
    sa.Column('file_update_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('file_md5'),
    sa.UniqueConstraint('file_md5')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('file_meta')
    # ### end Alembic commands ###
